<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-RG5Q252U" failures="1" tests="1" name="runners.RerunTestNGRunner" time="10.397" errors="0" timestamp="2022-11-07T04:35:14 IST" skipped="0">
  <testcase classname="runners.RerunTestNGRunner" name="runScenario" time="10.397">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at stepDef.FundingSocietiesStatisticsPageStepDef.verify_fulfilment_rate_is_displayed_to_the_user(FundingSocietiesStatisticsPageStepDef.java:40)
at âœ½.Verify Fulfilment Rate is displayed to the user(file:///C:/Users/91955/Git/Assignment/src/test/java/features/FundingSocietiesStatisticsPage.feature:39)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.RerunTestNGRunner -->
